In [18]:
#!jt -t grade3 -fs 24  -tfs 24 -ofs 22 -cellw 90%
!jt -r

Reset css and font defaults in:
/Users/Jie/.jupyter/custom &
/Users/Jie/Library/Jupyter/nbextensions


# Lecture 2 - Conditional Probability, Total Probability

- Discrete sequential models.
- Conditional probability.
- Total probability.

In [19]:
import random
import numpy as np
import numpy.random as npr

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

**<font color=blue>Example 2:</font>** Consider the experiment where we roll a 6-sided fair die 2 times and the event $E\equiv$observing a 1 or 2 on either roll.

Let's use simulation to calculate the relative frequency of this event.

In [20]:
num_sims = 1000
event_counter = 0
die_faces = [1,2,3,4,5,6]

for i in range(num_sims):
    die1 = random.choice(die_faces)
    die2 = random.choice(die_faces)
    if die1 <= 2 or die2 <=2:
        event_counter += 1
        
print("Relative frequency of getting a 1 or a 2 on either roll is ", event_counter/num_sims)
print("true probability is", 5/9)

Relative frequency of getting a 1 or a 2 on either roll is  0.537
true probability is 0.5555555555555556


In [21]:
# Alternatively
num_sims =10
?npr.randint
dice = npr.randint(1, 7, size= (2, num_sims))

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [22]:
dice

array([[6, 4, 3, 5, 6, 6, 5, 6, 5, 5],
       [6, 3, 2, 3, 1, 5, 5, 6, 1, 2]])

In [23]:
dice <= 2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False,  True, False, False, False,  True,
         True]])

In [24]:
?np.sum

Signature:
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used w

In [25]:
dice<=2
arry1= np.sum(dice<=2, axis =0)

In [26]:
arry1 >= 1

array([False, False,  True, False,  True, False, False, False,  True,
        True])

In [17]:
event_counts = np.sum(arry1>=1)
print("Probability of getting a 1 or 2 on either roll \
when rolling a fair 6-sided die twice= ", event_counts/num_sims
     )
print('True probability is ', 5/9)

Probability of getting a 1 or 2 on either roll when rolling a fair 6-sided die twice=  0.4
True probability is  0.5555555555555556


**<font color=blue>Example 3:</font>** Consider the experiment where we roll a 6-sided fair die 2 times and the event $E\equiv$at least one roll is 4.
Let's implement the random experiment to compute the relative frequency of the event.

In [28]:
num_sims = 1000
dice = npr.randint(1, 7, size=(2, num_sims))


array([[3, 1, 5, ..., 4, 2, 2],
       [1, 2, 1, ..., 5, 5, 1]])

In [29]:
dice == 4

array([[False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False]])

In [31]:
results =np.sum(dice ==4, axis =0)

In [34]:
event_counts = np.sum(results >=1)
event_counts

293

In [36]:


print("relative frequency of getting at one roll as 4 when rolling a fair 6-sided die twice= ", 
     event_counts/num_sims)
print('True probability is ', 11/36)

relative frequency of getting at one roll as 4 when rolling a fair 6-sided die twice=  0.293
True probability is  0.3055555555555556


 the following example is left as an exercise. Check your answer with this one.

**<font color=blue>Example 4:</font>** Consider the experiment where we flip a fair coin 3 times and the event $E\equiv$observing heads in the 2nd flip. 

In [ ]:




print("Probability of flipping a fair coin 3 times and observing heads in the 2nd flip= ", 
     event/num_sims)
print('True probability is ', ##)

## Conditional Probability


**<font color=blue>Example:</font> A magician has in her pocket a fair coin and a two-headed coin. She chooses one at random and flips it. What is the probability that the result is heads?**

Let's build a simulation to answer this:

**<font color=blue>Example:</font> Suppose that she chooses a coin at random. Using that coin, she flips it once and observes heads. What is the probability of observing heads in the second flip (using the same coin) if we observed heads in the first flip?**

Let's build a simulation to answer this: